### ISSUE TITLE
[Website] btrt box missing in coverage but present

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#19]
### Summary

The `btrt` box is said to not be tested, but that file https://gpac.github.io/mp4box.js/test/filereader.html?https://mpeggroup.github.io/FileFormatConformance/files/published/isobmff/21_segment.mp4 does have it.

### Steps to reproduce

Search for `btrt` you get
<img width="1382" alt="image" src="https://github.com/MPEGGroup/FileFormatConformance/assets/1830314/af338a00-3a96-46bb-bc10-9ced1e61d1d2">

but load the `21_segment.mp4` and you'll see it:
<img width="1009" alt="image" src="https://github.com/MPEGGroup/FileFormatConformance/assets/1830314/852baf71-0efd-44e4-a739-e43e825d6e96">

**Comment by DenizUgur** [comment]
This is a known bug at this moment. This is because the box `btrt` has defined a container of `SampleEntry` on standard features. However, there are no box that specify `SampleEntry` as its type (_explicitly_). The algorithm doesn't do a partial match but an exact match.

There are two ways to solve this problem:

1. Explicitly define each `SampleEntry` (e.g. `VisualSampleEntry`) for `btrt`. This would be an easy fix but at the same time we would deviate from specification.
2. Parse every available syntax to create a type hierarchy. Using that information, previous manual fix could be automated.

@podborski what do you think we should do here?

https://github.com/MPEGGroup/FileFormatConformance/blob/7c7c9abb3d795840a74027e67cd41dabb61b237f/data/standard_features/14496-12/boxes.json#L386-L392

**Comment by podborski** [comment]
Done in the last PR. Please re-open if problem still there.
